package Games;

import UserData.UserData;
import java.io.FileInputStream;
import java.io.InputStream;
import user_Interface.HomeGUI;
import user_Interface.JuniorAndSeniorGameSeletionGUI;
import user_Interface.Leaderboard;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import user_Interface.RateGUI;

public class ColourGUI extends javax.swing.JFrame {

    public UserData myUser = new UserData();

    private ColourGUI() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setUserData(UserData player) {
        this.myUser = player;
    }

    //DB conncetion
    Connection conn;
    String url = "jdbc:mysql://sql3.freemysqlhosting.net/";
    String db = "sql368113";
    String driver = "com.mysql.jdbc.Driver";
    String user = "sql368113";
    String pass = "qG9*eZ8*";

    int score;

    public ColourGUI(UserData player) {
        initComponents();
        setLocationRelativeTo(null);

        this.myUser = player;

        false1BtnRound2.setVisible(false);
        false2BtnRound2.setVisible(false);
        correctBtnRound2.setVisible(false);

        falseBtnRound3.setVisible(false);
        falseBtn2Round3.setVisible(false);
        correctRound3.setVisible(false);

        wellDoneLbl.setVisible(false);
        score = 0;

        try {
            // connect to db here stated above
            conn = DriverManager.getConnection(url + db, user, pass);
        } catch (SQLException e) {
            System.out.println("SQL Exception:" + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        questionLbl = new javax.swing.JLabel();
        correctBtnRound2 = new javax.swing.JButton();
        false2BtnRound2 = new javax.swing.JButton();
        false1BtnRound2 = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTa = new javax.swing.JTextArea();
        correctBtn1 = new javax.swing.JButton();
        false1Btn1 = new javax.swing.JButton();
        false2Btn1 = new javax.swing.JButton();
        correctRound3 = new javax.swing.JButton();
        falseBtnRound3 = new javax.swing.JButton();
        falseBtn2Round3 = new javax.swing.JButton();
        wellDoneLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        leaderBtn = new javax.swing.JButton();
        infoBtn = new javax.swing.JButton();
        progresslbl = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        rateBtn = new javax.swing.JButton();
        InfoSoundBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        questionLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        questionLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionLbl.setText("Which is True?");
        jPanel1.add(questionLbl);
        questionLbl.setBounds(320, 120, 219, 48);

        correctBtnRound2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        correctBtnRound2.setForeground(new java.awt.Color(255, 51, 255));
        correctBtnRound2.setText("This Is Pink");
        correctBtnRound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctBtnRound2ActionPerformed(evt);
            }
        });
        jPanel1.add(correctBtnRound2);
        correctBtnRound2.setBounds(70, 200, 180, 93);

        false2BtnRound2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        false2BtnRound2.setForeground(new java.awt.Color(255, 102, 102));
        false2BtnRound2.setText("This Is Blue");
        false2BtnRound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                false2BtnRound2ActionPerformed(evt);
            }
        });
        jPanel1.add(false2BtnRound2);
        false2BtnRound2.setBounds(340, 200, 170, 93);

        false1BtnRound2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        false1BtnRound2.setForeground(new java.awt.Color(51, 255, 204));
        false1BtnRound2.setText("This Is Grey");
        false1BtnRound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                false1BtnRound2ActionPerformed(evt);
            }
        });
        jPanel1.add(false1BtnRound2);
        false1BtnRound2.setBounds(600, 200, 180, 90);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeBtn.png"))); // NOI18N
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setMaximumSize(new java.awt.Dimension(85, 32));
        homeBtn.setMinimumSize(new java.awt.Dimension(85, 32));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn);
        homeBtn.setBounds(0, 0, 100, 41);

        displayTa.setColumns(20);
        displayTa.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        displayTa.setRows(5);
        jScrollPane1.setViewportView(displayTa);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(170, 330, 520, 120);

        correctBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        correctBtn1.setForeground(new java.awt.Color(0, 204, 0));
        correctBtn1.setText("This Is Green");
        correctBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(correctBtn1);
        correctBtn1.setBounds(600, 200, 180, 90);

        false1Btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        false1Btn1.setForeground(new java.awt.Color(204, 153, 0));
        false1Btn1.setText("This Is Blue");
        false1Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                false1Btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(false1Btn1);
        false1Btn1.setBounds(70, 200, 180, 93);

        false2Btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        false2Btn1.setForeground(new java.awt.Color(204, 0, 204));
        false2Btn1.setText("This Is red");
        false2Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                false2Btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(false2Btn1);
        false2Btn1.setBounds(340, 200, 170, 93);

        correctRound3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        correctRound3.setForeground(new java.awt.Color(255, 102, 0));
        correctRound3.setText("This is Orange");
        correctRound3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctRound3ActionPerformed(evt);
            }
        });
        jPanel1.add(correctRound3);
        correctRound3.setBounds(600, 200, 180, 90);

        falseBtnRound3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        falseBtnRound3.setForeground(new java.awt.Color(102, 255, 102));
        falseBtnRound3.setText("This is Cyan");
        falseBtnRound3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                falseBtnRound3ActionPerformed(evt);
            }
        });
        jPanel1.add(falseBtnRound3);
        falseBtnRound3.setBounds(340, 200, 170, 90);

        falseBtn2Round3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        falseBtn2Round3.setForeground(new java.awt.Color(102, 102, 0));
        falseBtn2Round3.setText("This is Red");
        falseBtn2Round3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                falseBtn2Round3ActionPerformed(evt);
            }
        });
        jPanel1.add(falseBtn2Round3);
        falseBtn2Round3.setBounds(70, 200, 180, 90);

        wellDoneLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        wellDoneLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wellDoneLbl.setText("Quiz Complete, Well Done");
        jPanel1.add(wellDoneLbl);
        wellDoneLbl.setBounds(180, 220, 470, 60);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backBtn.png"))); // NOI18N
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setMaximumSize(new java.awt.Dimension(85, 32));
        backBtn.setMinimumSize(new java.awt.Dimension(85, 32));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(100, 0, 90, 40);

        leaderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/leaderb.png"))); // NOI18N
        leaderBtn.setBorderPainted(false);
        leaderBtn.setContentAreaFilled(false);
        leaderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderBtnActionPerformed(evt);
            }
        });
        jPanel1.add(leaderBtn);
        leaderBtn.setBounds(380, 540, 140, 40);

        infoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/infoBtn.png"))); // NOI18N
        infoBtn.setBorderPainted(false);
        infoBtn.setContentAreaFilled(false);
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(infoBtn);
        infoBtn.setBounds(40, 540, 90, 40);

        progresslbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        progresslbl.setText("Progress");
        jPanel1.add(progresslbl);
        progresslbl.setBounds(740, 380, 110, 22);

        ProgressBar.setBackground(new java.awt.Color(255, 0, 0));
        ProgressBar.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.add(ProgressBar);
        ProgressBar.setBounds(710, 410, 146, 14);

        rateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rateb.png"))); // NOI18N
        rateBtn.setBorderPainted(false);
        rateBtn.setContentAreaFilled(false);
        rateBtn.setMaximumSize(new java.awt.Dimension(53, 23));
        rateBtn.setMinimumSize(new java.awt.Dimension(53, 23));
        rateBtn.setPreferredSize(new java.awt.Dimension(53, 23));
        rateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(rateBtn);
        rateBtn.setBounds(760, 543, 90, 40);

        InfoSoundBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/microphone.png"))); // NOI18N
        InfoSoundBtn.setMaximumSize(new java.awt.Dimension(50, 50));
        InfoSoundBtn.setMinimumSize(new java.awt.Dimension(50, 50));
        InfoSoundBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        InfoSoundBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoSoundBtnActionPerformed(evt);
            }
        });
        jPanel1.add(InfoSoundBtn);
        InfoSoundBtn.setBounds(60, 370, 50, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/colourBk.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //correct answer button
    private void correctBtnRound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctBtnRound2ActionPerformed
        score++;
        displayTa.setText("Correct Answer, good job " + myUser.getName() + "!!!\nIt took " + score + " turns to win! \nTry The Next Round");
        false1BtnRound2.setVisible(false);
        false2BtnRound2.setVisible(false);
        correctBtnRound2.setVisible(false);

        falseBtnRound3.setVisible(true);
        falseBtn2Round3.setVisible(true);
        correctRound3.setVisible(true);

        ProgressBar.setValue(66);
    }//GEN-LAST:event_correctBtnRound2ActionPerformed

    //fase answer button
    private void false1BtnRound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_false1BtnRound2ActionPerformed
        displayTa.setText("Sorry, Try Again " + myUser.getName() + "....");
        false1BtnRound2.setVisible(false);
        false2BtnRound2.setVisible(false);
        correctBtnRound2.setVisible(false);

        falseBtnRound3.setVisible(true);
        falseBtn2Round3.setVisible(true);
        correctRound3.setVisible(true);

        ProgressBar.setValue(66);
    }//GEN-LAST:event_false1BtnRound2ActionPerformed

    //home button
    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeGUI myHome = new HomeGUI(myUser);
        myHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    //false answer button
    private void false2BtnRound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_false2BtnRound2ActionPerformed
        displayTa.setText("Nope thats not it, try again " + myUser.getName() + "....");
        false1BtnRound2.setVisible(false);
        false2BtnRound2.setVisible(false);
        correctBtnRound2.setVisible(false);

        falseBtnRound3.setVisible(true);
        falseBtn2Round3.setVisible(true);
        correctRound3.setVisible(true);

        ProgressBar.setValue(66);
    }//GEN-LAST:event_false2BtnRound2ActionPerformed

    private void correctBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctBtn1ActionPerformed
        score++;

        displayTa.setText("Correct Answer, good job " + myUser.getName() + "!!!\nIt took " + score + " turns to win! \nTry The Next Round");
        false1Btn1.setVisible(false);
        false2Btn1.setVisible(false);
        correctBtn1.setVisible(false);

        false1BtnRound2.setVisible(true);
        false2BtnRound2.setVisible(true);
        correctBtnRound2.setVisible(true);

        ProgressBar.setValue(33);
    }//GEN-LAST:event_correctBtn1ActionPerformed

    private void false1Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_false1Btn1ActionPerformed
        displayTa.setText("Nope thats not it, try again " + myUser.getName() + "....");

        false1Btn1.setVisible(false);
        false2Btn1.setVisible(false);
        correctBtn1.setVisible(false);

        false1BtnRound2.setVisible(true);
        false2BtnRound2.setVisible(true);
        correctBtnRound2.setVisible(true);

        ProgressBar.setValue(33);
    }//GEN-LAST:event_false1Btn1ActionPerformed

    private void false2Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_false2Btn1ActionPerformed
        displayTa.setText("Sorry, Try Again " + myUser.getName() + "....");

        false1Btn1.setVisible(false);
        false2Btn1.setVisible(false);
        correctBtn1.setVisible(false);

        false1BtnRound2.setVisible(true);
        false2BtnRound2.setVisible(true);
        correctBtnRound2.setVisible(true);

        ProgressBar.setValue(33);
    }//GEN-LAST:event_false2Btn1ActionPerformed

    private void falseBtnRound3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_falseBtnRound3ActionPerformed
        ProgressBar.setValue(100);
        updateScore(score);
        displayTa.setText("Sorry, Try Again " + myUser.getName() + "....");
        falseBtnRound3.setVisible(false);
        falseBtn2Round3.setVisible(false);
        correctRound3.setVisible(false);

        wellDoneLbl.setVisible(true);
    }//GEN-LAST:event_falseBtnRound3ActionPerformed

    private void correctRound3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctRound3ActionPerformed
        ProgressBar.setValue(100);

        score++;
        updateScore(score);
        displayTa.setText("Correct Answer, good job " + myUser.getName() + "!!!\nIt took " + score + " turns to win!");

        falseBtnRound3.setVisible(false);
        falseBtn2Round3.setVisible(false);
        correctRound3.setVisible(false);

        wellDoneLbl.setVisible(true);
    }//GEN-LAST:event_correctRound3ActionPerformed

    private void falseBtn2Round3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_falseBtn2Round3ActionPerformed
        ProgressBar.setValue(100);
        updateScore(score);
        displayTa.setText("Nope thats not it, try again " + myUser.getName() + "....");
        falseBtnRound3.setVisible(false);
        falseBtn2Round3.setVisible(false);
        correctRound3.setVisible(false);

        wellDoneLbl.setVisible(true);
    }//GEN-LAST:event_falseBtn2Round3ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        JuniorAndSeniorGameSeletionGUI mySecectionGUI = new JuniorAndSeniorGameSeletionGUI(myUser);
        mySecectionGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void leaderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderBtnActionPerformed
        Leaderboard colourLeader = new Leaderboard(3);
        colourLeader.setVisible(true);
    }//GEN-LAST:event_leaderBtnActionPerformed

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Select the correct colour\nWhat is your favourite colour??", "Hint!!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_infoBtnActionPerformed

    private void rateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateBtnActionPerformed
        RateGUI myRateGUI = new RateGUI();
        myRateGUI.setVisible(true);
    }//GEN-LAST:event_rateBtnActionPerformed

    private void InfoSoundBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoSoundBtnActionPerformed
        try {
            // open the sound file as a Java input stream

            String audioFilePath = "src\\InfoSounds\\ColourGame.wav";
            InputStream in = new FileInputStream(audioFilePath);

            // create an audiostream from the inputstream
            AudioStream audioStream = new AudioStream(in);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        } catch (Exception e) {
            //Error Handeling
            System.out.println("Audio error: " + e);

        }
    }//GEN-LAST:event_InfoSoundBtnActionPerformed

    DBManager connectionManager = new DBManager();
    //storing users unique name and id , these will correspond to values in the DB, stored in userDAta class
    int uID;

    //method will connect to database and update score so it can be reflected in leaderboard class
    public void updateScore(int score) {
        uID = myUser.getUser_id();
        connectionManager.setConnection(conn);
        //select all fields from game scroe for only the currently logged in player and the game they are playing
        //and store results in resultset *GameID changes for every game its hard coded to DB
        ResultSet rs = connectionManager.Select_Query("select * from gameScore where user_id = " + uID + " AND GameID = 3;");
        ResultSet getCoins = connectionManager.Select_Query("select * from users where user_id = " + uID);

        try { //used to add coins if player gets 100%
            if (getCoins.next()) {
                int oldCoins = getCoins.getInt("coins");
                if (score == 3) {

                    int newCoins = oldCoins + 10;
                    connectionManager.Update_Query("UPDATE users SET coins = " + newCoins + " WHERE user_id = " + uID + ";");
                }
            }

            if (rs.next()) {
                //get the previous score on this game for this specific user
                int oldScore = rs.getInt("Score");
                //if oldscore is less than new score thenn we update DB to the new score                
                if (oldScore < score) {
                    connectionManager.Update_Query("UPDATE gameScore SET score = " + score + " WHERE GameID = 3 AND user_id = " + uID + ";");
                    endGame();
                } //possibly change this output??
                else if (score == 0) {
                    JOptionPane.showMessageDialog(null, "Hard luck, you didnt score,\nBetter luck next time");
                    endGame();

                } else if (score == oldScore) {
                    JOptionPane.showMessageDialog(null, "Not bad you got " + score + ", you've matched this score before");
                    endGame();

                } else if (oldScore > score) {
                    JOptionPane.showMessageDialog(null, "Not bad you got " + score + ", but not as good as your high score of " + oldScore);
                    endGame();

                } else {
                    JOptionPane.showMessageDialog(null, "Game over, you scored " + score + " out of 3");
                    endGame();

                }
            } else {
                //else if this particular user has not played this game before we insert new data 
                connectionManager.Update_Query("insert into gameScore values(" + 3 + ","
                        + "" + "'Colours Game'" + "," + uID + "," + score + ");");
                JOptionPane.showMessageDialog(null, "Game over you scored " + score);
                endGame();

            }
        } catch (SQLException ex) {
            Logger.getLogger(GeographyGameGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        connectionManager.closeConnection();
    }

    public void endGame() {
        JuniorAndSeniorGameSeletionGUI mySecectionGUI = new JuniorAndSeniorGameSeletionGUI(myUser);
        mySecectionGUI.setVisible(true);

        this.dispose();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColourGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColourGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColourGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColourGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColourGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InfoSoundBtn;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton correctBtn1;
    private javax.swing.JButton correctBtnRound2;
    private javax.swing.JButton correctRound3;
    private javax.swing.JTextArea displayTa;
    private javax.swing.JButton false1Btn1;
    private javax.swing.JButton false1BtnRound2;
    private javax.swing.JButton false2Btn1;
    private javax.swing.JButton false2BtnRound2;
    private javax.swing.JButton falseBtn2Round3;
    private javax.swing.JButton falseBtnRound3;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton infoBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leaderBtn;
    private javax.swing.JLabel progresslbl;
    private javax.swing.JLabel questionLbl;
    private javax.swing.JButton rateBtn;
    private javax.swing.JLabel wellDoneLbl;
    // End of variables declaration//GEN-END:variables

}
