package Games;

import UserData.UserData;
import user_Interface.FirstAndSecondGameSelection;
import user_Interface.HomeGUI;
import user_Interface.Leaderboard;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import user_Interface.RateGUI;

public class SoundGameGUI extends javax.swing.JFrame {

    public UserData myUser = new UserData();

    private SoundGameGUI() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setUserData(UserData player) {
        this.myUser = player;
    }

    //DB conncetion
    Connection conn;
    String url = "jdbc:mysql://sql3.freemysqlhosting.net/";
    String db = "sql368113";
    String driver = "com.mysql.jdbc.Driver";
    String user = "sql368113";
    String pass = "qG9*eZ8*";

    //questions & answers
    private String Questions;
    private String[] Answer1;
    private String[] Answer2;
    private String[] Answer3;

    private String[] Correct;
    private String response;

    // set the count and score
    int count = 0;
    int score = 0;
    int round = 1;

    public SoundGameGUI(UserData player) {
        initComponents();
        setLocationRelativeTo(null);

        this.myUser = player;

        Questions = new String();
        Answer1 = new String[6];
        Answer2 = new String[6];
        Answer3 = new String[6];

        Correct = new String[6];

        try {
            // connect to db here stated above
            conn = DriverManager.getConnection(url + db, user, pass);
        } catch (SQLException e) {
            System.out.println("SQL Exception:" + e.toString());
        }
    }

    public void setAnswers(String Questions, String Answer1[], String Answer2[], String Answer3[], String Correct[]) {
        this.Questions = Questions;
        this.Answer1 = Answer1;
        this.Answer2 = Answer2;
        this.Answer3 = Answer3;

        this.Correct = Correct;

        //start question in array posistion 0
        questionsLbl.setText(Questions);
        answer1Rtbn.setText(Answer1[0]);
        answer2Rtbn.setText(Answer2[0]);
        answer3Rtbn.setText(Answer3[0]);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        HomeBtn = new javax.swing.JButton();
        questionsLbl = new javax.swing.JLabel();
        answer1Rtbn = new javax.swing.JRadioButton();
        answer2Rtbn = new javax.swing.JRadioButton();
        answer3Rtbn = new javax.swing.JRadioButton();
        nextBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        leaderBtn = new javax.swing.JButton();
        infoBtn = new javax.swing.JButton();
        progresslbl = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        rateBtn = new javax.swing.JButton();
        InfoSoundBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeBtn.png"))); // NOI18N
        HomeBtn.setBorderPainted(false);
        HomeBtn.setContentAreaFilled(false);
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBtn);
        HomeBtn.setBounds(10, 10, 90, 40);

        questionsLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        questionsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionsLbl.setText("Questions Displayed here");
        jPanel1.add(questionsLbl);
        questionsLbl.setBounds(240, 70, 422, 65);

        answer1Rtbn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(answer1Rtbn);
        answer1Rtbn.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        answer1Rtbn.setText("jRadioButton1");
        answer1Rtbn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        answer1Rtbn.setBorderPainted(true);
        answer1Rtbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1RtbnActionPerformed(evt);
            }
        });
        jPanel1.add(answer1Rtbn);
        answer1Rtbn.setBounds(390, 200, 120, 30);

        answer2Rtbn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(answer2Rtbn);
        answer2Rtbn.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        answer2Rtbn.setText("jRadioButton1");
        answer2Rtbn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        answer2Rtbn.setBorderPainted(true);
        answer2Rtbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2RtbnActionPerformed(evt);
            }
        });
        jPanel1.add(answer2Rtbn);
        answer2Rtbn.setBounds(390, 260, 120, 30);

        answer3Rtbn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(answer3Rtbn);
        answer3Rtbn.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        answer3Rtbn.setText("jRadioButton1");
        answer3Rtbn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        answer3Rtbn.setBorderPainted(true);
        answer3Rtbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer3RtbnActionPerformed(evt);
            }
        });
        jPanel1.add(answer3Rtbn);
        answer3Rtbn.setBounds(390, 320, 120, 30);

        nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nextBtn.png"))); // NOI18N
        nextBtn.setBorderPainted(false);
        nextBtn.setContentAreaFilled(false);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextBtn);
        nextBtn.setBounds(350, 380, 200, 90);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backBtn.png"))); // NOI18N
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setMaximumSize(new java.awt.Dimension(85, 32));
        backBtn.setMinimumSize(new java.awt.Dimension(85, 32));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(110, 10, 90, 40);

        leaderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/leaderb.png"))); // NOI18N
        leaderBtn.setBorderPainted(false);
        leaderBtn.setContentAreaFilled(false);
        leaderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderBtnActionPerformed(evt);
            }
        });
        jPanel1.add(leaderBtn);
        leaderBtn.setBounds(20, 540, 120, 40);

        infoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/infoBtn.png"))); // NOI18N
        infoBtn.setBorderPainted(false);
        infoBtn.setContentAreaFilled(false);
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(infoBtn);
        infoBtn.setBounds(790, 530, 90, 41);

        progresslbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        progresslbl.setText("Progress");
        jPanel1.add(progresslbl);
        progresslbl.setBounds(420, 500, 110, 22);

        ProgressBar.setBackground(new java.awt.Color(255, 0, 0));
        ProgressBar.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.add(ProgressBar);
        ProgressBar.setBounds(390, 530, 146, 14);

        rateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rateb.png"))); // NOI18N
        rateBtn.setBorderPainted(false);
        rateBtn.setContentAreaFilled(false);
        rateBtn.setMaximumSize(new java.awt.Dimension(53, 23));
        rateBtn.setMinimumSize(new java.awt.Dimension(53, 23));
        rateBtn.setPreferredSize(new java.awt.Dimension(53, 23));
        rateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(rateBtn);
        rateBtn.setBounds(670, 530, 100, 40);

        InfoSoundBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/microphone.png"))); // NOI18N
        InfoSoundBtn.setMaximumSize(new java.awt.Dimension(50, 50));
        InfoSoundBtn.setMinimumSize(new java.awt.Dimension(50, 50));
        InfoSoundBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        InfoSoundBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoSoundBtnActionPerformed(evt);
            }
        });
        jPanel1.add(InfoSoundBtn);
        InfoSoundBtn.setBounds(740, 400, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/soundG.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        HomeGUI myHome = new HomeGUI(myUser);
        myHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void playDogSound() {
        try {
            // open the sound file as a Java input stream

            String AudioFilePath = "src\\Sounds\\Dog.wav";
            InputStream in = new FileInputStream(AudioFilePath);

            // create an audiostream from the inputstream
            AudioStream audioStream = new AudioStream(in);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        } catch (Exception e) {
            //Error Handeling
            System.out.println("Audio error: " + e);
        }
    }

    private void playCatSound() {
        try {
            // open the sound file as a Java input stream

            String audioFilePath = "src\\Sounds\\Cat.wav";
            InputStream in = new FileInputStream(audioFilePath);

            // create an audiostream from the inputstream
            AudioStream audioStream = new AudioStream(in);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        } catch (Exception e) {
            //Error Handeling
            System.out.println("Audio error: " + e);
        }
    }

    private void playWolfSound() {
        try {
            // open the sound file as a Java input stream

            String audioFilePath = "src\\Sounds\\Wolf.wav";
            InputStream in = new FileInputStream(audioFilePath);

            // create an audiostream from the inputstream
            AudioStream audioStream = new AudioStream(in);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        } catch (Exception e) {
            //Error Handeling
            System.out.println("Audio error: " + e);

        }
    }

    private void playBirdSound() {
        try {
            // open the sound file as a Java input stream

            String audioFilePath = "src\\Sounds\\Bird.wav";
            InputStream in = new FileInputStream(audioFilePath);

            // create an audiostream from the inputstream
            AudioStream audioStream = new AudioStream(in);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        } catch (Exception e) {
            //Error Handeling
            System.out.println("Audio error: " + e);

        }
    }

    private void playCowSound() {
        try {
            // open the sound file as a Java input stream

            String audioFilePath = "src\\Sounds\\Cow.wav";
            InputStream in = new FileInputStream(audioFilePath);

            // create an audiostream from the inputstream
            AudioStream audioStream = new AudioStream(in);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        } catch (Exception e) {
            //Error Handeling
            System.out.println("Audio error: " + e);

        }
    }

    private void playPigSound() {
        try {
            // open the sound file as a Java input stream

            String audioFilePath = "src\\Sounds\\Pig.wav";
            InputStream in = new FileInputStream(audioFilePath);

            // create an audiostream from the inputstream
            AudioStream audioStream = new AudioStream(in);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        } catch (Exception e) {
            //Error Handeling
            System.out.println("Audio error: " + e);

        }
    }

    private void playSheepSound() {
        try {
            // open the sound file as a Java input stream

            String audioFilePath = "src\\Sounds\\Sheep.wav";
            InputStream in = new FileInputStream(audioFilePath);

            // create an audiostream from the inputstream
            AudioStream audioStream = new AudioStream(in);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        } catch (Exception e) {
            //Error Handeling
            System.out.println("Audio error: " + e);

        }
    }

    private void playHorseSound() {
        try {
            // open the sound file as a Java input stream

            String audioFilePath = "src\\Sounds\\Horse.wav";
            InputStream in = new FileInputStream(audioFilePath);

            // create an audiostream from the inputstream
            AudioStream audioStream = new AudioStream(in);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        } catch (Exception e) {
            //Error Handeling
            System.out.println("Audio error: " + e);

        }
    }

    private void playDuckSound() {
        try {
            // open the sound file as a Java input stream

            String audioFilePath = "src\\Sounds\\Duck.wav";
            InputStream in = new FileInputStream(audioFilePath);

            // create an audiostream from the inputstream
            AudioStream audioStream = new AudioStream(in);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        } catch (Exception e) {
            //Error Handeling
            System.out.println("Audio error: " + e);

        }
    }

    private void answer1RtbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1RtbnActionPerformed
        //Switch statment exectutes a diffrent animal sound method based on what round it is.
        //Round incremented with every click of Next button

        switch (round) {
            case 1:
                playDogSound();
                break;
            case 2:
                playCowSound();
                break;
            case 3:
                playWolfSound();
                break;
            case 4:
                playPigSound();
                break;
            case 5:
                playBirdSound();
                break;
        }

    }//GEN-LAST:event_answer1RtbnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        //increment the round so ther app knows to play a diff fset of sounds for each radio button
        round++;

        //go through buttons find what is selected
        for (Enumeration<AbstractButton> buttons = buttonGroup1.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                response = button.getText();
                if (Correct[count].equals(response)) {
                    score++;
                }
                ProgressBar.setValue(ProgressBar.getValue() + 20);

                count++;
            } //end if
        } //end for

        // set end of game.. do something else here, show a scoreboard or something
        if (count == 5) {
            updateScore(score);
        } else {
            //run through the questions 
            questionsLbl.setText(Questions);
            answer1Rtbn.setText(Answer1[count]);
            answer2Rtbn.setText(Answer2[count]);
            answer3Rtbn.setText(Answer3[count]);
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void answer2RtbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2RtbnActionPerformed
        //Switch statment exectutes a diffrent animal sound method based on what round it is.
        //Round incremented with every click of Next button

        switch (round) {
            case 1:
                playPigSound();
                break;
            case 2:
                playHorseSound();
                break;
            case 3:
                playPigSound();
                break;
            case 4:
                playDogSound();
                break;
            case 5:
                playHorseSound();
                break;
        }
    }//GEN-LAST:event_answer2RtbnActionPerformed

    private void answer3RtbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer3RtbnActionPerformed
        //Switch statment exectutes a diffrent animal sound method based on what round it is.
        //Round incremented with every click of Next button

        switch (round) {
            case 1:
                playDuckSound();
                break;
            case 2:
                playCatSound();
                break;
            case 3:
                playCatSound();
                break;
            case 4:
                playDuckSound();
                break;
            case 5:
                playPigSound();
                break;
        }

    }//GEN-LAST:event_answer3RtbnActionPerformed

//instances and variables used in following updateScore method which connects to DB
    DBManager connectionManager = new DBManager();
    //storing users unique name and id , these will correspond to values in the DB, stored in userDAta class
    String uName = myUser.getName();
    int uID;

    public void updateScore(int score) {
        uID = myUser.getUser_id();
        connectionManager.setConnection(conn);
        //select all fields from game scroe for only the currently logged in player and the game they are playing
        //and store results in resultset GameID is hardcoded into DB 6 = numbergame
        ResultSet rs = connectionManager.Select_Query("select * from gameScore where user_id = " + uID + " AND GameID = 6;");
        ResultSet getCoins = connectionManager.Select_Query("select * from users where user_id = " + uID);

        try { //used to add coins if player gets 100%
            if (getCoins.next()) {
                int oldCoins = getCoins.getInt("coins");
                if (score == 6) {

                    int newCoins = oldCoins + 10;
                    connectionManager.Update_Query("UPDATE users SET coins = " + newCoins + " WHERE user_id = " + uID + ";");
                }
            }
            if (rs.next()) {
                //get the previous score on this game for this specific user
                int oldScore = rs.getInt("Score");
                //if oldscore is less than new score thenn we update DB to the new score
                if (oldScore < score) {
                    connectionManager.Update_Query("UPDATE gameScore SET score = " + score + " WHERE GameID = 6 AND user_id = " + uID + ";");
                    JOptionPane.showMessageDialog(null, "You scored: " + score + " out of 6 \nGame Over");
                    endGame();

                } //0nce your dont get the same score twice in a row do following
                else if (score != oldScore) {
                    JOptionPane.showMessageDialog(null, "You scored: " + score + "out of 6 \nGame Over\nNot bad, but not as good as your high score of " + oldScore);
                    endGame();

                }
            } else {
                //else if this particular user has not played this game before we insert new data 
                connectionManager.Update_Query("insert into gameScore values(" + 6 + ","
                        + "" + "'Sound Game'" + "," + uID + "," + score + ");");
                JOptionPane.showMessageDialog(null, "You scored: " + score + " out of 6 \nGame Over");
                endGame();
            }
        } catch (SQLException ex) {
            Logger.getLogger(SoundGameGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        FirstAndSecondGameSelection mySecectionGUI = new FirstAndSecondGameSelection(myUser);
        mySecectionGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void leaderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderBtnActionPerformed
        Leaderboard numberLeader = new Leaderboard(6);
        numberLeader.setVisible(true);
    }//GEN-LAST:event_leaderBtnActionPerformed

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Listen carfully and see what word matches the correct animal noise", "Hint!!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_infoBtnActionPerformed

    private void rateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateBtnActionPerformed
        RateGUI myRateGUI = new RateGUI();
        myRateGUI.setVisible(true);
    }//GEN-LAST:event_rateBtnActionPerformed

    private void InfoSoundBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoSoundBtnActionPerformed
        try {
            // open the sound file as a Java input stream

            String audioFilePath = "src\\InfoSounds\\SoundGame.wav";
            InputStream in = new FileInputStream(audioFilePath);

            // create an audiostream from the inputstream
            AudioStream audioStream = new AudioStream(in);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        } catch (Exception e) {
            //Error Handeling
            System.out.println("Audio error: " + e);

        }
    }//GEN-LAST:event_InfoSoundBtnActionPerformed

    public void endGame() {
        FirstAndSecondGameSelection mySecectionGUI = new FirstAndSecondGameSelection(myUser);
        mySecectionGUI.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoundGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoundGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoundGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoundGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoundGameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeBtn;
    private javax.swing.JButton InfoSoundBtn;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JRadioButton answer1Rtbn;
    private javax.swing.JRadioButton answer2Rtbn;
    private javax.swing.JRadioButton answer3Rtbn;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton infoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton leaderBtn;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel progresslbl;
    private javax.swing.JLabel questionsLbl;
    private javax.swing.JButton rateBtn;
    // End of variables declaration//GEN-END:variables
}