package Games;

import UserData.UserData;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import user_Interface.HomeGUI;
import user_Interface.ThirdAndForthGameSeletionGUI;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import user_Interface.Leaderboard;
import user_Interface.RateGUI;

public class TimeGUI extends javax.swing.JFrame {

    //questions & answers
    private String[] Questions;
    private String[] Answer1;
    private String[] Answer2;
    private String[] Answer3;
    private String[] Answer4;
    private String[] Correct;
    private String response;

    public UserData myUser = new UserData();

    private TimeGUI() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setUserData(UserData player) {
        this.myUser = player;
    }

    // set the count and score
    int count = 0;
    int score = 0;

    //DB conncetion
    Connection conn;
    String url = "jdbc:mysql://sql3.freemysqlhosting.net/";
    String db = "sql368113";
    String driver = "com.mysql.jdbc.Driver";
    String user = "sql368113";
    String pass = "qG9*eZ8*";

    public TimeGUI(UserData player) {
        initComponents();
        setLocationRelativeTo(null);

        this.myUser = player;

        Questions = new String[6];
        Answer1 = new String[6];
        Answer2 = new String[6];
        Answer3 = new String[6];
        Answer4 = new String[6];
        Correct = new String[6];

        try {
            // connect to db here stated above
            conn = DriverManager.getConnection(url + db, user, pass);
        } catch (SQLException e) {
            System.out.println("SQL Exception:" + e.toString());
        }
    }

    //get questions and answers from gameselection GUI (/this can be changed to any class if wanted)
    public void setAnswers(String Questions[], String Answer1[], String Answer2[], String Answer3[], String Answer4[], String Correct[]) {
        this.Questions = Questions;
        this.Answer1 = Answer1;
        this.Answer2 = Answer2;
        this.Answer3 = Answer3;
        this.Answer4 = Answer4;
        this.Correct = Correct;

        //start question in array posistion 0
        questionsLbl.setText(Questions[0]);
        answer1Rtbn.setText(Answer1[0]);
        answer2Rtbn.setText(Answer2[0]);
        answer3Rtbn.setText(Answer3[0]);
        answer4Rtbn.setText(Answer4[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nextBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionsLbl = new javax.swing.JTextArea();
        answer1Rtbn = new javax.swing.JRadioButton();
        answer2Rtbn = new javax.swing.JRadioButton();
        answer3Rtbn = new javax.swing.JRadioButton();
        answer4Rtbn = new javax.swing.JRadioButton();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        infoBtn = new javax.swing.JButton();
        leaderBtn = new javax.swing.JButton();
        rateBtn = new javax.swing.JButton();
        InfoSoundBtn = new javax.swing.JButton();
        ProgressBar = new javax.swing.JProgressBar();
        progresslbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nextBtn.png"))); // NOI18N
        nextBtn.setBorderPainted(false);
        nextBtn.setContentAreaFilled(false);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextBtn);
        nextBtn.setBounds(370, 440, 210, 90);

        questionsLbl.setColumns(20);
        questionsLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        questionsLbl.setLineWrap(true);
        questionsLbl.setRows(5);
        questionsLbl.setWrapStyleWord(true);
        jScrollPane1.setViewportView(questionsLbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 100, 510, 170);

        buttonGroup1.add(answer1Rtbn);
        answer1Rtbn.setSelected(true);
        answer1Rtbn.setText("jRadioButton1");
        answer1Rtbn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        answer1Rtbn.setBorderPainted(true);
        getContentPane().add(answer1Rtbn);
        answer1Rtbn.setBounds(370, 300, 200, 23);

        buttonGroup1.add(answer2Rtbn);
        answer2Rtbn.setText("jRadioButton1");
        answer2Rtbn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        answer2Rtbn.setBorderPainted(true);
        getContentPane().add(answer2Rtbn);
        answer2Rtbn.setBounds(370, 330, 200, 23);

        buttonGroup1.add(answer3Rtbn);
        answer3Rtbn.setText("jRadioButton1");
        answer3Rtbn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        answer3Rtbn.setBorderPainted(true);
        getContentPane().add(answer3Rtbn);
        answer3Rtbn.setBounds(370, 360, 200, 23);

        buttonGroup1.add(answer4Rtbn);
        answer4Rtbn.setText("jRadioButton1");
        answer4Rtbn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        answer4Rtbn.setBorderPainted(true);
        getContentPane().add(answer4Rtbn);
        answer4Rtbn.setBounds(370, 390, 200, 23);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeBtn.png"))); // NOI18N
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setMaximumSize(new java.awt.Dimension(85, 32));
        homeBtn.setMinimumSize(new java.awt.Dimension(85, 32));
        homeBtn.setPreferredSize(new java.awt.Dimension(85, 32));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(homeBtn);
        homeBtn.setBounds(0, 0, 90, 40);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backBtn.png"))); // NOI18N
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setMaximumSize(new java.awt.Dimension(85, 32));
        backBtn.setMinimumSize(new java.awt.Dimension(85, 32));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(100, 0, 90, 40);

        infoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/infoBtn.png"))); // NOI18N
        infoBtn.setBorderPainted(false);
        infoBtn.setContentAreaFilled(false);
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(infoBtn);
        infoBtn.setBounds(770, 490, 90, 41);

        leaderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/leaderb.png"))); // NOI18N
        leaderBtn.setBorderPainted(false);
        leaderBtn.setContentAreaFilled(false);
        leaderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(leaderBtn);
        leaderBtn.setBounds(140, 490, 120, 40);

        rateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rateb.png"))); // NOI18N
        rateBtn.setBorderPainted(false);
        rateBtn.setContentAreaFilled(false);
        rateBtn.setMaximumSize(new java.awt.Dimension(53, 23));
        rateBtn.setMinimumSize(new java.awt.Dimension(53, 23));
        rateBtn.setPreferredSize(new java.awt.Dimension(53, 23));
        rateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(rateBtn);
        rateBtn.setBounds(650, 490, 90, 40);

        InfoSoundBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/microphone.png"))); // NOI18N
        InfoSoundBtn.setMaximumSize(new java.awt.Dimension(50, 50));
        InfoSoundBtn.setMinimumSize(new java.awt.Dimension(50, 50));
        InfoSoundBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        InfoSoundBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoSoundBtnActionPerformed(evt);
            }
        });
        getContentPane().add(InfoSoundBtn);
        InfoSoundBtn.setBounds(740, 330, 50, 50);

        ProgressBar.setBackground(new java.awt.Color(255, 51, 51));
        ProgressBar.setForeground(new java.awt.Color(51, 255, 51));
        getContentPane().add(ProgressBar);
        ProgressBar.setBounds(130, 350, 146, 14);

        progresslbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        progresslbl.setText("Progress");
        getContentPane().add(progresslbl);
        progresslbl.setBounds(160, 320, 110, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/timeG.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed

        //go through buttons find what is selected
        for (Enumeration<AbstractButton> buttons = buttonGroup1.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                response = button.getText();
                if (Correct[count].equals(response)) {
                    //if correct tell me
                    score++;

                }
                count++;
                ProgressBar.setValue(ProgressBar.getValue() + 17);

            } //end if
        } //end for

        // set end of game.. do something else here, show a scoreboard or something
        if (count == 6) {
            JOptionPane.showMessageDialog(null, "game over \n your score is: " + score + " out of 6");
            updateScore(score);
            endGame();
        } else {

            //run through the questions..
            questionsLbl.setText(Questions[count]);
            answer1Rtbn.setText(Answer1[count]);
            answer2Rtbn.setText(Answer2[count]);
            answer3Rtbn.setText(Answer3[count]);
            answer4Rtbn.setText(Answer4[count]);
        }

    }//GEN-LAST:event_nextBtnActionPerformed

    //db stuff
    DBManager connectionManager = new DBManager();
    //storing users unique name and id , these will correspond to values in the DB, stored in userDAta class
    String uName = myUser.getName();
    int uID;

    //method will connect to database and update score so it can be reflected in leaderboard class
    public void updateScore(int score) {
        uID = myUser.getUser_id();
        connectionManager.setConnection(conn);
        //select all fields from game scroe for only the currently logged in player and the game they are playing
        //and store results in resultset
        ResultSet rs = connectionManager.Select_Query("select * from gameScore where user_id = " + uID + " AND GameID = 7;");
        ResultSet getCoins = connectionManager.Select_Query("select * from users where user_id = " + uID);

        try { //used to add coins if player gets 100%
            if (getCoins.next()) {
                int oldCoins = getCoins.getInt("coins");
                if (score == 6) {

                    int newCoins = oldCoins + 10;
                    connectionManager.Update_Query("UPDATE users SET coins = " + newCoins + " WHERE user_id = " + uID + ";");
                }
            }
            if (rs.next()) {
                //get the previous score on this game for this specific user
                int oldScore = rs.getInt("Score");
                //if oldscore is less than new score thenn we update DB to the new score
                if (oldScore < score) {
                    connectionManager.Update_Query("UPDATE gameScore SET score = " + score + " WHERE GameID = 7 AND user_id = " + uID + ";");
                } //possibly change this output??
                else {
                    JOptionPane.showMessageDialog(null, "Not bad, but not as good as your high score of " + oldScore);
                }
            } else {
                //else if this particular user has not played this game before we insert new data 
                connectionManager.Update_Query("insert into gameScore values(" + 7 + ","
                        + "" + "'Geography Game'" + "," + uID + "," + score + ");");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TimeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeGUI myHome = new HomeGUI(myUser);
        myHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        ThirdAndForthGameSeletionGUI mySecectionGUI = new ThirdAndForthGameSeletionGUI(myUser);
        mySecectionGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Test your time telling skills\n select the right answer!", "Hint!!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_infoBtnActionPerformed

    private void rateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateBtnActionPerformed
        RateGUI myRateGUI = new RateGUI();
        myRateGUI.setVisible(true);
    }//GEN-LAST:event_rateBtnActionPerformed

    private void InfoSoundBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoSoundBtnActionPerformed
        try {
            // open the sound file as a Java input stream

            String audioFilePath = "src\\InfoSounds\\TimeGame.wav";
            InputStream in = new FileInputStream(audioFilePath);

            // create an audiostream from the inputstream
            AudioStream audioStream = new AudioStream(in);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        } catch (Exception e) {
            //Error Handeling
            System.out.println("Audio error: " + e);
        }
    }//GEN-LAST:event_InfoSoundBtnActionPerformed

    private void leaderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderBtnActionPerformed
        Leaderboard geoLeader = new Leaderboard(7);
        geoLeader.setVisible(true);
    }//GEN-LAST:event_leaderBtnActionPerformed

    public void endGame() {
        ThirdAndForthGameSeletionGUI mySecectionGUI = new ThirdAndForthGameSeletionGUI(myUser);
        mySecectionGUI.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InfoSoundBtn;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JRadioButton answer1Rtbn;
    private javax.swing.JRadioButton answer2Rtbn;
    private javax.swing.JRadioButton answer3Rtbn;
    private javax.swing.JRadioButton answer4Rtbn;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton infoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leaderBtn;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel progresslbl;
    private javax.swing.JTextArea questionsLbl;
    private javax.swing.JButton rateBtn;
    // End of variables declaration//GEN-END:variables
}