package user_Interface;

import Games.GeographyGameGUI;
import Games.SearchGameGUI;
import Games.SoundGameGUI;
import UserData.UserData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class FirstAndSecondGameSelection extends javax.swing.JFrame {

    public UserData myUser = new UserData();

    private FirstAndSecondGameSelection() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setUserData(UserData player) {
        this.myUser = player;
    }

    GeographyGameGUI myGeoGame;
    SearchGameGUI mySearchGame;
    SoundGameGUI mySoundGame;

    // for avatar image
    ImageIcon image;
    String avatar;
    String uName;

    //DB conncetion
    Connection conn;
    String url = "jdbc:mysql://sql3.freemysqlhosting.net/";
    String db = "sql368113";
    String driver = "com.mysql.jdbc.Driver";
    String user = "sql368113";
    String pass = "qG9*eZ8*";

    public FirstAndSecondGameSelection(UserData player) {
        initComponents();
        setLocationRelativeTo(null);

        AvailableTa.setVisible(false);

        this.myUser = player;

        //get name for start of database connection
        uName = myUser.getName();

        try {
            // connect to db here stated above
            conn = DriverManager.getConnection(url + db, user, pass);
        } catch (SQLException e) {
            System.out.println("SQL Exception:" + e.toString());
        }

        getPlayer();

        //set name
        nameLbl.setText(uName);

        //set avatar
        avatar = myUser.getAvatar();
        image = new ImageIcon(avatar);
        avatarLbl.setIcon(image);

        //set coins
        int coins = myUser.getCoins();
        String CoinTxt = String.valueOf(coins);
        coinsLbl.setText(CoinTxt + " coins");
    }

    public void getPlayer() {
        try {

            Statement st = conn.createStatement();
            ResultSet rs1 = st.executeQuery("select * from users WHERE name = '" + uName + "';");
            if (rs1.next()) {
                myUser.setCoins(rs1.getInt("coins"));
            } else {
                System.out.println("error test 1");
            }
        } catch (SQLException ex) {
            Logger.getLogger(FirstAndSecondGameSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        geographyBtn = new javax.swing.JRadioButton();
        searchBtn = new javax.swing.JRadioButton();
        soundBtn = new javax.swing.JRadioButton();
        launchBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        selectionLbl1 = new javax.swing.JLabel();
        avatarLbl = new javax.swing.JLabel();
        ProfileBtn = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        coinsPicLbl = new javax.swing.JLabel();
        coinsLbl = new javax.swing.JLabel();
        AvailableTa = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeBtn.png"))); // NOI18N
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn);
        homeBtn.setBounds(0, 0, 85, 32);

        buttonGroup1.add(geographyBtn);
        geographyBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        geographyBtn.setText("Geography Game");
        geographyBtn.setOpaque(false);
        geographyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geographyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(geographyBtn);
        geographyBtn.setBounds(370, 200, 220, 27);

        buttonGroup1.add(searchBtn);
        searchBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        searchBtn.setText("Search Game");
        searchBtn.setOpaque(false);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchBtn);
        searchBtn.setBounds(370, 250, 150, 27);

        buttonGroup1.add(soundBtn);
        soundBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        soundBtn.setText("Sound Game");
        soundBtn.setOpaque(false);
        soundBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundBtnActionPerformed(evt);
            }
        });
        jPanel1.add(soundBtn);
        soundBtn.setBounds(370, 300, 140, 27);

        launchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LAUNCHbtn.png"))); // NOI18N
        launchBtn.setBorderPainted(false);
        launchBtn.setContentAreaFilled(false);
        launchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(launchBtn);
        launchBtn.setBounds(380, 400, 180, 90);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backBtn.png"))); // NOI18N
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setMaximumSize(new java.awt.Dimension(85, 32));
        backBtn.setMinimumSize(new java.awt.Dimension(85, 32));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(90, 0, 85, 32);

        selectionLbl1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        selectionLbl1.setText("Select one game and press \"LAUNCH GAME\" to begin");
        jPanel1.add(selectionLbl1);
        selectionLbl1.setBounds(250, 120, 450, 32);

        avatarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guest.png"))); // NOI18N
        jPanel1.add(avatarLbl);
        avatarLbl.setBounds(670, 0, 80, 100);

        ProfileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileB.png"))); // NOI18N
        ProfileBtn.setBorderPainted(false);
        ProfileBtn.setContentAreaFilled(false);
        ProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ProfileBtn);
        ProfileBtn.setBounds(760, 70, 120, 40);

        nameLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        nameLbl.setText("Name");
        jPanel1.add(nameLbl);
        nameLbl.setBounds(760, 10, 120, 21);

        coinsPicLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coins.png"))); // NOI18N
        jPanel1.add(coinsPicLbl);
        coinsPicLbl.setBounds(760, 30, 30, 30);

        coinsLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(coinsLbl);
        coinsLbl.setBounds(800, 34, 70, 20);

        AvailableTa.setBackground(new java.awt.Color(102, 255, 204));
        AvailableTa.setColumns(20);
        AvailableTa.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        AvailableTa.setLineWrap(true);
        AvailableTa.setRows(5);
        AvailableTa.setText("Coins available in this game!");
        AvailableTa.setWrapStyleWord(true);
        AvailableTa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(AvailableTa);
        AvailableTa.setBounds(600, 250, 170, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ageSel.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeGUI myHome = new HomeGUI(myUser);
        myHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed


    private void launchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchBtnActionPerformed
        if (geographyBtn.isSelected()) {
            myGeoGame = new GeographyGameGUI(myUser);
            myGeoGame.setVisible(true);

            // set questions and answers for time game
            String GeoQuestion = "What Country is The following landmark from";
            String[] GeoAnswer1 = {"France", "Germany", "Ireland", "Russia", "Egypt", "England"};
            String[] GeoAnswer2 = {"England", "Sweeden", "USA", "Thailand", "Brazil", "Sweeden"};
            String[] GeoAnswer3 = {"Spain", "England", "Brazil", "Uganda", "Mexico", "China"};
            String[] GeoAnswer4 = {"Greece", "S. Africa", "China", "USA", "Norway", "Scotland"};
            String[] GeoCorrect = {"France", "England", "Brazil", "USA", "Egypt", "China"};
            myGeoGame.setAnswers(GeoQuestion, GeoAnswer1, GeoAnswer2, GeoAnswer3, GeoAnswer4, GeoCorrect);
        } else if (searchBtn.isSelected()) {
            mySearchGame = new SearchGameGUI(myUser);
            mySearchGame.setVisible(true);
        } else {
            mySoundGame = new SoundGameGUI(myUser);
            mySoundGame.setVisible(true);

            //Set Questions and Answers for Sound Game
            String SoundQuestion = "Match the right animal with its sound";
            String[] SoundAnswer1 = {"Dog", "Wolf", "Elephant", "Horse", "Birds"};
            String[] SoundAnswer2 = {"Wale", "Horse", "Pig", "Tiger", "Cat"};
            String[] SoundAnswer3 = {"Wolf", "Rat", "monkey", "Duck", "Dog"};

            String[] SoundCorrect = {"Dog", "Horse", "Pig", "Duck", "Birds"};
            mySoundGame.setAnswers(SoundQuestion, SoundAnswer1, SoundAnswer2, SoundAnswer3, SoundCorrect);
        }
        this.dispose();
    }//GEN-LAST:event_launchBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        ChildAgeSelectionGUI mySecectionGUI = new ChildAgeSelectionGUI(myUser);
        mySecectionGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void ProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileBtnActionPerformed
        if (uName.equals("Guest")) {
            JOptionPane.showMessageDialog(null, "You must be logged in to access profile");

        } else {
            Profile selectionGUI = new Profile(myUser);
            selectionGUI.setUserData(myUser);
            selectionGUI.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ProfileBtnActionPerformed

    private void geographyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geographyBtnActionPerformed
        AvailableTa.setVisible(true);
    }//GEN-LAST:event_geographyBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        AvailableTa.setVisible(true);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void soundBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundBtnActionPerformed
        AvailableTa.setVisible(true);
    }//GEN-LAST:event_soundBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstAndSecondGameSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstAndSecondGameSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstAndSecondGameSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstAndSecondGameSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstAndSecondGameSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AvailableTa;
    private javax.swing.JButton ProfileBtn;
    private javax.swing.JLabel avatarLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel coinsLbl;
    private javax.swing.JLabel coinsPicLbl;
    private javax.swing.JRadioButton geographyBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton launchBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JRadioButton searchBtn;
    private javax.swing.JLabel selectionLbl1;
    private javax.swing.JRadioButton soundBtn;
    // End of variables declaration//GEN-END:variables
}