package user_Interface;

import UserData.UserData;

public class HomeGUI extends javax.swing.JFrame {

    public UserData myUser = new UserData();

    public HomeGUI(UserData player) {
        initComponents();

        setLocationRelativeTo(null);
        this.myUser = player;
    }

    private HomeGUI() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        launchChildBtn = new javax.swing.JButton();
        launchParentBtn = new javax.swing.JButton();
        whoLbl = new javax.swing.JTextField();
        bckgrLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(373, 352));
        setResizable(false);
        getContentPane().setLayout(null);

        launchChildBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        launchChildBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/childButton.png"))); // NOI18N
        launchChildBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        launchChildBtn.setBorderPainted(false);
        launchChildBtn.setContentAreaFilled(false);
        launchChildBtn.setMaximumSize(new java.awt.Dimension(85, 32));
        launchChildBtn.setMinimumSize(new java.awt.Dimension(85, 32));
        launchChildBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchChildBtnActionPerformed(evt);
            }
        });
        getContentPane().add(launchChildBtn);
        launchChildBtn.setBounds(130, 240, 120, 33);

        launchParentBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        launchParentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/parentButton.png"))); // NOI18N
        launchParentBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        launchParentBtn.setBorderPainted(false);
        launchParentBtn.setContentAreaFilled(false);
        launchParentBtn.setMaximumSize(new java.awt.Dimension(85, 32));
        launchParentBtn.setMinimumSize(new java.awt.Dimension(85, 32));
        launchParentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchParentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(launchParentBtn);
        launchParentBtn.setBounds(130, 180, 120, 40);

        whoLbl.setEditable(false);
        whoLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        whoLbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        whoLbl.setText("Who are you?");
        whoLbl.setBorder(null);
        whoLbl.setOpaque(false);
        getContentPane().add(whoLbl);
        whoLbl.setBounds(130, 120, 130, 30);

        bckgrLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edugamesCloud.png"))); // NOI18N
        getContentPane().add(bckgrLbl);
        bckgrLbl.setBounds(0, 0, 370, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void launchChildBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchChildBtnActionPerformed
        ChildAgeSelectionGUI selectionGUI = new ChildAgeSelectionGUI(myUser);
        selectionGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_launchChildBtnActionPerformed

    private void launchParentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchParentBtnActionPerformed
        ParentSelectionGUI parentGUI = new ParentSelectionGUI(myUser);
        parentGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_launchParentBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bckgrLbl;
    private javax.swing.JButton launchChildBtn;
    private javax.swing.JButton launchParentBtn;
    private javax.swing.JTextField whoLbl;
    // End of variables declaration//GEN-END:variables
}