package user_Interface;

import Games.DBManager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;

public class Leaderboard extends javax.swing.JFrame {

    //DB conncetion
    Connection conn;
    String url = "jdbc:mysql://sql3.freemysqlhosting.net/";
    String db = "sql368113";
    String driver = "com.mysql.jdbc.Driver";
    String user = "sql368113";
    String pass = "qG9*eZ8*";
    int gameID;

    //we pass the gameID of said game into constructor this way we can use this one leaderboard class for every game
    public Leaderboard(int gameID) {
        this.gameID = gameID;
        initComponents();
        setLocationRelativeTo(null);

        try {
            // connect to db here stated above
            conn = DriverManager.getConnection(url + db, user, pass);
            getLeaderBoard();
        } catch (SQLException e) {
            System.out.println("SQL Exception:" + e.toString());
        }

    }

    DBManager connectionManager = new DBManager();
    ResultSet rs1;

    //Jframe needs a non overloaded constructor also to function this does nothing but just needs to be here
    private Leaderboard() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void getLeaderBoard() throws SQLException {
        connectionManager.setConnection(conn);
        String query = "SELECT GameName, Score, name FROM gameScore, users WHERE users.user_id = gameScore.user_id and GameID=" + gameID + " ORDER BY Score DESC;";
        rs1 = connectionManager.Select_Query(query);

        ResultSetMetaData rsmd = rs1.getMetaData();

        //get num of coloums for the loop
        int numberOfColumns = rsmd.getColumnCount();

        //getting headings 
        displayTA.append("-------------------------------------------------------\n");
        for (int i = 1; i <= numberOfColumns; i++) {
            if (i > 1) {
                displayTA.append(",             ");
            }
            String columnName = rsmd.getColumnName(i);
            displayTA.append(columnName);
            //start a new line if the last colum heading is reached
            if (i == numberOfColumns) {
                displayTA.append("\n");
            }
        }
        displayTA.append("-------------------------------------------------------");
        displayTA.append("\n");

        while (rs1.next()) {
            for (int i = 1; i <= numberOfColumns; i++) {
                if (i > 1) {
                    displayTA.append("    ||      ");
                }
                String columnValue = rs1.getString(i);
                displayTA.append(columnValue);
                if (i == numberOfColumns) {
                    displayTA.append("\n");
                }
            }
        }
        displayTA.append("-------------------------------------------------------");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        closeBtn = new javax.swing.JButton();
        bkgrLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 330));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 330));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 330));
        jPanel1.setLayout(null);

        displayTA.setEditable(false);
        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(109, 88, 292, 154);

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeBtn.setBorderPainted(false);
        closeBtn.setContentAreaFilled(false);
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(closeBtn);
        closeBtn.setBounds(400, 260, 92, 41);

        bkgrLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/leader.png"))); // NOI18N
        jPanel1.add(bkgrLbl);
        bkgrLbl.setBounds(0, 0, 500, 320);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-4, -4, 500, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leaderboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bkgrLbl;
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}