package user_Interface;

import UserData.UserData;

public class OutdoorActivitiesGUI extends javax.swing.JFrame {

    public UserData myUser = new UserData();

    public OutdoorActivitiesGUI(UserData player) {
        initComponents();
        setLocationRelativeTo(null);

        this.myUser = player;
    }

    private OutdoorActivitiesGUI() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        homeLbl = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        imageLbl4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        imageLbl5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        homeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeBtnGrey.png"))); // NOI18N
        homeLbl.setBorderPainted(false);
        homeLbl.setContentAreaFilled(false);
        homeLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeLblActionPerformed(evt);
            }
        });
        jPanel1.add(homeLbl);
        homeLbl.setBounds(0, 0, 90, 40);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backBtnGrey.png"))); // NOI18N
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(100, 0, 90, 40);

        imageLbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stuckinthemud.png"))); // NOI18N
        imageLbl4.setMaximumSize(new java.awt.Dimension(200, 200));
        imageLbl4.setMinimumSize(new java.awt.Dimension(200, 200));
        imageLbl4.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(imageLbl4);
        imageLbl4.setBounds(50, 200, 170, 130);

        jTextArea5.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText("This is a variation of the classic tag game. One team are the chasers and the other are runners. If the chaser catches a runner the runner must stay in place with their legs open. When another runner crawls through the stuck players legs they are then free to run again. The game ends when all players are \"stuck in the mud\"");
        jTextArea5.setWrapStyleWord(true);
        jScrollPane5.setViewportView(jTextArea5);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(250, 210, 630, 100);

        imageLbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/redrover.png"))); // NOI18N
        imageLbl5.setMaximumSize(new java.awt.Dimension(200, 200));
        imageLbl5.setMinimumSize(new java.awt.Dimension(200, 200));
        imageLbl5.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(imageLbl5);
        imageLbl5.setBounds(50, 420, 170, 130);

        jTextArea6.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextArea6.setLineWrap(true);
        jTextArea6.setRows(5);
        jTextArea6.setText("Divide the children into two teams and choose a leader for each team. The kids form into two parallel lines opposite each other, and join hands.\nThe leader of one team chooses one player from the opposite team and invites them to play by calling \"red rover, red rover, let child's name come over!\"\nThat player called then runs at the opposing team and tries to hurl himself through the children, breaking the chain. If he fails, he joins that chain, and the turn passes to the other side.");
        jTextArea6.setWrapStyleWord(true);
        jScrollPane6.setViewportView(jTextArea6);

        jPanel1.add(jScrollPane6);
        jScrollPane6.setBounds(250, 430, 630, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nightBk.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeLblActionPerformed
        HomeGUI myHome = new HomeGUI(myUser);
        myHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeLblActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        ParentSelectionGUI parentGUI = new ParentSelectionGUI(myUser);
        parentGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutdoorActivitiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutdoorActivitiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutdoorActivitiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutdoorActivitiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutdoorActivitiesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton homeLbl;
    private javax.swing.JLabel imageLbl4;
    private javax.swing.JLabel imageLbl5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    // End of variables declaration//GEN-END:variables
}