package user_Interface;

import UserData.UserData;

public class ParentSelectionGUI extends javax.swing.JFrame {

    public UserData myUser = new UserData();

    public ParentSelectionGUI(UserData player) {
        initComponents();
        setLocationRelativeTo(null);

        this.myUser = player;
    }

    private ParentSelectionGUI() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IndoorBtn = new javax.swing.JButton();
        OutdoorBtn = new javax.swing.JButton();
        FoodBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        IndoorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/indoorBtn.png"))); // NOI18N
        IndoorBtn.setBorderPainted(false);
        IndoorBtn.setContentAreaFilled(false);
        IndoorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndoorBtnActionPerformed(evt);
            }
        });
        jPanel1.add(IndoorBtn);
        IndoorBtn.setBounds(90, 290, 180, 110);

        OutdoorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/outdoorBtn.png"))); // NOI18N
        OutdoorBtn.setBorderPainted(false);
        OutdoorBtn.setContentAreaFilled(false);
        OutdoorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutdoorBtnActionPerformed(evt);
            }
        });
        jPanel1.add(OutdoorBtn);
        OutdoorBtn.setBounds(360, 300, 200, 90);

        FoodBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/foodbtn.png"))); // NOI18N
        FoodBtn.setBorderPainted(false);
        FoodBtn.setContentAreaFilled(false);
        FoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodBtnActionPerformed(evt);
            }
        });
        jPanel1.add(FoodBtn);
        FoodBtn.setBounds(640, 290, 180, 110);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeBtnGrey.png"))); // NOI18N
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setMaximumSize(new java.awt.Dimension(85, 32));
        homeBtn.setMinimumSize(new java.awt.Dimension(85, 32));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn);
        homeBtn.setBounds(0, 0, 90, 40);

        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(240, 240, 240));
        jTextField1.setText("Please Select An Option");
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(360, 180, 197, 27);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nightBk.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 900, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IndoorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndoorBtnActionPerformed
        IndoorActivitiesGUI selectionGUI = new IndoorActivitiesGUI(myUser);
        selectionGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IndoorBtnActionPerformed

    private void OutdoorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutdoorBtnActionPerformed
        OutdoorActivitiesGUI selectionGUI = new OutdoorActivitiesGUI(myUser);
        selectionGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OutdoorBtnActionPerformed
    //back to home screen button
    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeGUI myHome = new HomeGUI(myUser);
        myHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void FoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodBtnActionPerformed
        FoodTipsGUI selectionGUI = new FoodTipsGUI(myUser);
        selectionGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FoodBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParentSelectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParentSelectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParentSelectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParentSelectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParentSelectionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FoodBtn;
    private javax.swing.JButton IndoorBtn;
    private javax.swing.JButton OutdoorBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}