package user_Interface;

import Games.DBManager;
import UserData.UserData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Profile extends javax.swing.JFrame {

    public UserData myUser = new UserData();

    private Profile() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setUserData(UserData player) {
        this.myUser = player;
    }
    //DB conncetion
    Connection conn;
    String url = "jdbc:mysql://sql3.freemysqlhosting.net/";
    String db = "sql368113";
    String driver = "com.mysql.jdbc.Driver";
    String user = "sql368113";
    String pass = "qG9*eZ8*";

    // for avatar image
    ImageIcon image;
    String avatar;
    int coins;

    public Profile(UserData player) {
        initComponents();
        setLocationRelativeTo(null);

        this.myUser = player;

        //set name
        String uName = myUser.getName();
        nameLbl.setText(uName);

        //set avatar
        avatar = myUser.getAvatar();
        image = new ImageIcon(avatar);
        avatarLbl.setIcon(image);

        //set coins
        coins = myUser.getCoins();
        String CoinTxt = String.valueOf(coins);
        coinsLbl.setText(CoinTxt + " coins");

        try {
            // connect to db here stated above
            conn = DriverManager.getConnection(url + db, user, pass);
        } catch (SQLException e) {
            System.out.println("SQL Exception:" + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        avatarLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Kid1 = new javax.swing.JButton();
        Kid2 = new javax.swing.JButton();
        Kid3 = new javax.swing.JButton();
        Kid4 = new javax.swing.JButton();
        Kid5 = new javax.swing.JButton();
        Kid6 = new javax.swing.JButton();
        Kid7 = new javax.swing.JButton();
        Kid8 = new javax.swing.JButton();
        Kid9 = new javax.swing.JButton();
        Kid10 = new javax.swing.JButton();
        Kid11 = new javax.swing.JButton();
        Kid12 = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        coinsLbl = new javax.swing.JLabel();
        coinsPicLbl = new javax.swing.JLabel();
        moreLbl = new javax.swing.JLabel();
        coinsPicLbl2 = new javax.swing.JLabel();
        coinsPicLbl3 = new javax.swing.JLabel();
        coinsPicLbl4 = new javax.swing.JLabel();
        coinsPicLbl5 = new javax.swing.JLabel();
        coinsPicLbl6 = new javax.swing.JLabel();
        coinsPicLbl7 = new javax.swing.JLabel();
        priceLbl1 = new javax.swing.JLabel();
        priceLbl2 = new javax.swing.JLabel();
        priceLbl3 = new javax.swing.JLabel();
        priceLbl4 = new javax.swing.JLabel();
        priceLbl5 = new javax.swing.JLabel();
        priceLbl6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeBtn.png"))); // NOI18N
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn);
        homeBtn.setBounds(0, 0, 85, 32);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backBtn.png"))); // NOI18N
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setMaximumSize(new java.awt.Dimension(85, 32));
        backBtn.setMinimumSize(new java.awt.Dimension(85, 32));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(90, 0, 85, 32);

        avatarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guest.png"))); // NOI18N
        jPanel1.add(avatarLbl);
        avatarLbl.setBounds(670, 0, 80, 100);

        nameLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        nameLbl.setText("Name");
        jPanel1.add(nameLbl);
        nameLbl.setBounds(760, 10, 120, 21);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("Change Avatar:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 190, 140, 30);

        Kid1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kid1.png"))); // NOI18N
        Kid1.setBorder(null);
        Kid1.setMaximumSize(new java.awt.Dimension(80, 100));
        Kid1.setMinimumSize(new java.awt.Dimension(80, 100));
        Kid1.setPreferredSize(new java.awt.Dimension(80, 100));
        Kid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kid1ActionPerformed(evt);
            }
        });
        jPanel1.add(Kid1);
        Kid1.setBounds(130, 240, 80, 100);

        Kid2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kid2.png"))); // NOI18N
        Kid2.setMaximumSize(new java.awt.Dimension(80, 100));
        Kid2.setMinimumSize(new java.awt.Dimension(80, 100));
        Kid2.setPreferredSize(new java.awt.Dimension(80, 100));
        Kid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kid2ActionPerformed(evt);
            }
        });
        jPanel1.add(Kid2);
        Kid2.setBounds(240, 240, 80, 100);

        Kid3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kid3.png"))); // NOI18N
        Kid3.setMaximumSize(new java.awt.Dimension(80, 100));
        Kid3.setMinimumSize(new java.awt.Dimension(80, 100));
        Kid3.setPreferredSize(new java.awt.Dimension(80, 100));
        Kid3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kid3ActionPerformed(evt);
            }
        });
        jPanel1.add(Kid3);
        Kid3.setBounds(340, 240, 80, 100);

        Kid4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kid4.png"))); // NOI18N
        Kid4.setMaximumSize(new java.awt.Dimension(80, 100));
        Kid4.setMinimumSize(new java.awt.Dimension(80, 100));
        Kid4.setPreferredSize(new java.awt.Dimension(80, 100));
        Kid4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kid4ActionPerformed(evt);
            }
        });
        jPanel1.add(Kid4);
        Kid4.setBounds(460, 240, 80, 100);

        Kid5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kid5.png"))); // NOI18N
        Kid5.setMaximumSize(new java.awt.Dimension(80, 100));
        Kid5.setMinimumSize(new java.awt.Dimension(80, 100));
        Kid5.setPreferredSize(new java.awt.Dimension(80, 100));
        Kid5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kid5ActionPerformed(evt);
            }
        });
        jPanel1.add(Kid5);
        Kid5.setBounds(580, 240, 80, 100);

        Kid6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kid6.png"))); // NOI18N
        Kid6.setMaximumSize(new java.awt.Dimension(80, 100));
        Kid6.setMinimumSize(new java.awt.Dimension(80, 100));
        Kid6.setPreferredSize(new java.awt.Dimension(80, 100));
        Kid6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kid6ActionPerformed(evt);
            }
        });
        jPanel1.add(Kid6);
        Kid6.setBounds(690, 240, 80, 100);

        Kid7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kid7.png"))); // NOI18N
        Kid7.setBorder(null);
        Kid7.setMaximumSize(new java.awt.Dimension(80, 100));
        Kid7.setMinimumSize(new java.awt.Dimension(80, 100));
        Kid7.setPreferredSize(new java.awt.Dimension(80, 100));
        Kid7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kid7ActionPerformed(evt);
            }
        });
        jPanel1.add(Kid7);
        Kid7.setBounds(130, 360, 80, 100);

        Kid8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kid8.png"))); // NOI18N
        Kid8.setBorder(null);
        Kid8.setMaximumSize(new java.awt.Dimension(80, 100));
        Kid8.setMinimumSize(new java.awt.Dimension(80, 100));
        Kid8.setPreferredSize(new java.awt.Dimension(80, 100));
        Kid8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kid8ActionPerformed(evt);
            }
        });
        jPanel1.add(Kid8);
        Kid8.setBounds(240, 360, 80, 100);

        Kid9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kid9.png"))); // NOI18N
        Kid9.setBorder(null);
        Kid9.setMaximumSize(new java.awt.Dimension(80, 100));
        Kid9.setMinimumSize(new java.awt.Dimension(80, 100));
        Kid9.setPreferredSize(new java.awt.Dimension(80, 100));
        Kid9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kid9ActionPerformed(evt);
            }
        });
        jPanel1.add(Kid9);
        Kid9.setBounds(340, 360, 80, 100);

        Kid10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kid10.png"))); // NOI18N
        Kid10.setBorder(null);
        Kid10.setMaximumSize(new java.awt.Dimension(80, 100));
        Kid10.setMinimumSize(new java.awt.Dimension(80, 100));
        Kid10.setPreferredSize(new java.awt.Dimension(80, 100));
        Kid10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kid10ActionPerformed(evt);
            }
        });
        jPanel1.add(Kid10);
        Kid10.setBounds(460, 360, 80, 100);

        Kid11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kid11.png"))); // NOI18N
        Kid11.setBorder(null);
        Kid11.setMaximumSize(new java.awt.Dimension(80, 100));
        Kid11.setMinimumSize(new java.awt.Dimension(80, 100));
        Kid11.setPreferredSize(new java.awt.Dimension(80, 100));
        Kid11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kid11ActionPerformed(evt);
            }
        });
        jPanel1.add(Kid11);
        Kid11.setBounds(580, 360, 80, 100);

        Kid12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kid12.png"))); // NOI18N
        Kid12.setBorder(null);
        Kid12.setMaximumSize(new java.awt.Dimension(80, 100));
        Kid12.setMinimumSize(new java.awt.Dimension(80, 100));
        Kid12.setPreferredSize(new java.awt.Dimension(80, 100));
        Kid12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kid12ActionPerformed(evt);
            }
        });
        jPanel1.add(Kid12);
        Kid12.setBounds(690, 360, 80, 100);

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn);
        saveBtn.setBounds(380, 510, 120, 40);

        coinsLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(coinsLbl);
        coinsLbl.setBounds(800, 34, 70, 20);

        coinsPicLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coins.png"))); // NOI18N
        jPanel1.add(coinsPicLbl);
        coinsPicLbl.setBounds(760, 30, 30, 30);

        moreLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        moreLbl.setText("To get more coins get 100% in each game");
        jPanel1.add(moreLbl);
        moreLbl.setBounds(260, 120, 420, 21);

        coinsPicLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coins.png"))); // NOI18N
        jPanel1.add(coinsPicLbl2);
        coinsPicLbl2.setBounds(130, 460, 30, 30);

        coinsPicLbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coins.png"))); // NOI18N
        jPanel1.add(coinsPicLbl3);
        coinsPicLbl3.setBounds(240, 460, 30, 30);

        coinsPicLbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coins.png"))); // NOI18N
        jPanel1.add(coinsPicLbl4);
        coinsPicLbl4.setBounds(340, 460, 30, 30);

        coinsPicLbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coins.png"))); // NOI18N
        jPanel1.add(coinsPicLbl5);
        coinsPicLbl5.setBounds(460, 460, 30, 30);

        coinsPicLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coins.png"))); // NOI18N
        jPanel1.add(coinsPicLbl6);
        coinsPicLbl6.setBounds(580, 460, 30, 30);

        coinsPicLbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coins.png"))); // NOI18N
        jPanel1.add(coinsPicLbl7);
        coinsPicLbl7.setBounds(690, 460, 30, 30);

        priceLbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        priceLbl1.setText("20");
        jPanel1.add(priceLbl1);
        priceLbl1.setBounds(170, 470, 40, 20);

        priceLbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        priceLbl2.setText("40");
        jPanel1.add(priceLbl2);
        priceLbl2.setBounds(280, 470, 40, 20);

        priceLbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        priceLbl3.setText("50");
        jPanel1.add(priceLbl3);
        priceLbl3.setBounds(380, 470, 40, 20);

        priceLbl4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        priceLbl4.setText("70");
        jPanel1.add(priceLbl4);
        priceLbl4.setBounds(500, 470, 40, 20);

        priceLbl5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        priceLbl5.setText("90");
        jPanel1.add(priceLbl5);
        priceLbl5.setBounds(620, 470, 40, 20);

        priceLbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        priceLbl6.setText("110");
        jPanel1.add(priceLbl6);
        priceLbl6.setBounds(730, 470, 40, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ageSel.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeGUI myHome = new HomeGUI(myUser);
        myHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed


    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        ChildAgeSelectionGUI mySecectionGUI = new ChildAgeSelectionGUI(myUser);
        mySecectionGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void Kid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kid1ActionPerformed

        avatar = "src/Images/kid1.png";
        image = new ImageIcon(avatar);
        avatarLbl.setIcon(image);

        Kid1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        Kid2.setBorder(null);
        Kid3.setBorder(null);
        Kid4.setBorder(null);
        Kid5.setBorder(null);
        Kid6.setBorder(null);
        Kid7.setBorder(null);
        Kid8.setBorder(null);
        Kid9.setBorder(null);
        Kid10.setBorder(null);
        Kid11.setBorder(null);
        Kid12.setBorder(null);
    }//GEN-LAST:event_Kid1ActionPerformed

    private void Kid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kid2ActionPerformed
        avatar = "src/Images/kid2.png";
        image = new ImageIcon(avatar);
        avatarLbl.setIcon(image);

        Kid1.setBorder(null);
        Kid2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        Kid3.setBorder(null);
        Kid4.setBorder(null);
        Kid5.setBorder(null);
        Kid6.setBorder(null);
        Kid7.setBorder(null);
        Kid8.setBorder(null);
        Kid9.setBorder(null);
        Kid10.setBorder(null);
        Kid11.setBorder(null);
        Kid12.setBorder(null);
    }//GEN-LAST:event_Kid2ActionPerformed

    private void Kid3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kid3ActionPerformed
        avatar = "src/Images/kid3.png";
        image = new ImageIcon(avatar);
        avatarLbl.setIcon(image);

        Kid1.setBorder(null);
        Kid2.setBorder(null);
        Kid3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        Kid4.setBorder(null);
        Kid5.setBorder(null);
        Kid6.setBorder(null);
        Kid7.setBorder(null);
        Kid8.setBorder(null);
        Kid9.setBorder(null);
        Kid10.setBorder(null);
        Kid11.setBorder(null);
        Kid12.setBorder(null);
    }//GEN-LAST:event_Kid3ActionPerformed

    private void Kid4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kid4ActionPerformed
        avatar = "src/Images/kid4.png";
        image = new ImageIcon(avatar);
        avatarLbl.setIcon(image);

        Kid1.setBorder(null);
        Kid2.setBorder(null);
        Kid3.setBorder(null);
        Kid4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        Kid5.setBorder(null);
        Kid6.setBorder(null);
        Kid7.setBorder(null);
        Kid8.setBorder(null);
        Kid9.setBorder(null);
        Kid10.setBorder(null);
        Kid11.setBorder(null);
        Kid12.setBorder(null);
    }//GEN-LAST:event_Kid4ActionPerformed

    private void Kid5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kid5ActionPerformed
        avatar = "src/Images/kid5.png";
        image = new ImageIcon(avatar);
        avatarLbl.setIcon(image);

        Kid1.setBorder(null);
        Kid2.setBorder(null);
        Kid3.setBorder(null);
        Kid4.setBorder(null);
        Kid5.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        Kid6.setBorder(null);
        Kid7.setBorder(null);
        Kid8.setBorder(null);
        Kid9.setBorder(null);
        Kid10.setBorder(null);
        Kid11.setBorder(null);
        Kid12.setBorder(null);
    }//GEN-LAST:event_Kid5ActionPerformed

    private void Kid6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kid6ActionPerformed
        avatar = "src/Images/kid6.png";
        image = new ImageIcon(avatar);
        avatarLbl.setIcon(image);

        Kid1.setBorder(null);
        Kid2.setBorder(null);
        Kid3.setBorder(null);
        Kid4.setBorder(null);
        Kid5.setBorder(null);
        Kid6.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        Kid7.setBorder(null);
        Kid8.setBorder(null);
        Kid9.setBorder(null);
        Kid10.setBorder(null);
        Kid11.setBorder(null);
        Kid12.setBorder(null);
    }//GEN-LAST:event_Kid6ActionPerformed

    //db stuff
    DBManager connectionManager = new DBManager();
    //storing users unique name and id , these will correspond to values in the DB, stored in userDAta class
    int uID;

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed

        uID = myUser.getUser_id();
        connectionManager.setConnection(conn);
        ResultSet rs = connectionManager.Select_Query("select * from users where user_id = " + uID + ";");

        try { //if there is a next position do following
            if (rs.next()) {

                connectionManager.Update_Query("UPDATE users SET avatar = '" + avatar + "' WHERE user_id = " + uID + ";");
                JOptionPane.showMessageDialog(null, "Your avatar has been changed");

                ChildAgeSelectionGUI mySecectionGUI = new ChildAgeSelectionGUI(myUser);
                mySecectionGUI.setVisible(true);
                this.dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
        connectionManager.closeConnection();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void Kid7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kid7ActionPerformed
        if (coins >= 20) {

            avatar = "src/Images/kid7.png";
            image = new ImageIcon(avatar);
            avatarLbl.setIcon(image);
        } else {
            JOptionPane.showMessageDialog(null, "You need 20 coins to unlock this avatar \nKeep Playing");

        }

        Kid1.setBorder(null);
        Kid2.setBorder(null);
        Kid3.setBorder(null);
        Kid4.setBorder(null);
        Kid5.setBorder(null);
        Kid6.setBorder(null);
        Kid7.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        Kid8.setBorder(null);
        Kid9.setBorder(null);
        Kid10.setBorder(null);
        Kid11.setBorder(null);
        Kid12.setBorder(null);
    }//GEN-LAST:event_Kid7ActionPerformed

    private void Kid8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kid8ActionPerformed
        if (coins >= 40) {

            avatar = "src/Images/kid8.png";
            image = new ImageIcon(avatar);
            avatarLbl.setIcon(image);
        } else {
            JOptionPane.showMessageDialog(null, "You need 40 coins to unlock this avatar \nKeep Playing");

        }
        Kid1.setBorder(null);
        Kid2.setBorder(null);
        Kid3.setBorder(null);
        Kid4.setBorder(null);
        Kid5.setBorder(null);
        Kid6.setBorder(null);
        Kid7.setBorder(null);
        Kid8.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        Kid9.setBorder(null);
        Kid10.setBorder(null);
        Kid11.setBorder(null);
        Kid12.setBorder(null);
    }//GEN-LAST:event_Kid8ActionPerformed

    private void Kid9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kid9ActionPerformed
        if (coins >= 50) {

            avatar = "src/Images/kid9.png";
            image = new ImageIcon(avatar);
            avatarLbl.setIcon(image);
        } else {
            JOptionPane.showMessageDialog(null, "You need 50 coins to unlock this avatar \nKeep Playing");

        }
        Kid1.setBorder(null);
        Kid2.setBorder(null);
        Kid3.setBorder(null);
        Kid4.setBorder(null);
        Kid5.setBorder(null);
        Kid6.setBorder(null);
        Kid7.setBorder(null);
        Kid8.setBorder(null);
        Kid9.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        Kid10.setBorder(null);
        Kid11.setBorder(null);
        Kid12.setBorder(null);
    }//GEN-LAST:event_Kid9ActionPerformed

    private void Kid10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kid10ActionPerformed
        if (coins >= 70) {

            avatar = "src/Images/kid10.png";
            image = new ImageIcon(avatar);
            avatarLbl.setIcon(image);
        } else {
            JOptionPane.showMessageDialog(null, "You need 70 coins to unlock this avatar \nKeep Playing");

        }
        Kid1.setBorder(null);
        Kid2.setBorder(null);
        Kid3.setBorder(null);
        Kid4.setBorder(null);
        Kid5.setBorder(null);
        Kid6.setBorder(null);
        Kid7.setBorder(null);
        Kid8.setBorder(null);
        Kid9.setBorder(null);
        Kid10.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        Kid11.setBorder(null);
        Kid12.setBorder(null);
    }//GEN-LAST:event_Kid10ActionPerformed

    private void Kid11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kid11ActionPerformed
        if (coins >= 90) {

            avatar = "src/Images/kid11.png";
            image = new ImageIcon(avatar);
            avatarLbl.setIcon(image);
        } else {
            JOptionPane.showMessageDialog(null, "You need 90 coins to unlock this avatar \nKeep Playing");

        }
        Kid1.setBorder(null);
        Kid2.setBorder(null);
        Kid3.setBorder(null);
        Kid4.setBorder(null);
        Kid5.setBorder(null);
        Kid6.setBorder(null);
        Kid7.setBorder(null);
        Kid8.setBorder(null);
        Kid9.setBorder(null);
        Kid10.setBorder(null);
        Kid11.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
        Kid12.setBorder(null);
    }//GEN-LAST:event_Kid11ActionPerformed

    private void Kid12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kid12ActionPerformed
        if (coins >= 110) {

            avatar = "src/Images/kid12.png";
            image = new ImageIcon(avatar);
            avatarLbl.setIcon(image);
        } else {
            JOptionPane.showMessageDialog(null, "You need 110 coins to unlock this avatar \nKeep Playing");

        }
        Kid1.setBorder(null);
        Kid2.setBorder(null);
        Kid3.setBorder(null);
        Kid4.setBorder(null);
        Kid5.setBorder(null);
        Kid6.setBorder(null);
        Kid7.setBorder(null);
        Kid8.setBorder(null);
        Kid9.setBorder(null);
        Kid10.setBorder(null);
        Kid11.setBorder(null);
        Kid12.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));
    }//GEN-LAST:event_Kid12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kid1;
    private javax.swing.JButton Kid10;
    private javax.swing.JButton Kid11;
    private javax.swing.JButton Kid12;
    private javax.swing.JButton Kid2;
    private javax.swing.JButton Kid3;
    private javax.swing.JButton Kid4;
    private javax.swing.JButton Kid5;
    private javax.swing.JButton Kid6;
    private javax.swing.JButton Kid7;
    private javax.swing.JButton Kid8;
    private javax.swing.JButton Kid9;
    private javax.swing.JLabel avatarLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel coinsLbl;
    private javax.swing.JLabel coinsPicLbl;
    private javax.swing.JLabel coinsPicLbl2;
    private javax.swing.JLabel coinsPicLbl3;
    private javax.swing.JLabel coinsPicLbl4;
    private javax.swing.JLabel coinsPicLbl5;
    private javax.swing.JLabel coinsPicLbl6;
    private javax.swing.JLabel coinsPicLbl7;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel moreLbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel priceLbl1;
    private javax.swing.JLabel priceLbl2;
    private javax.swing.JLabel priceLbl3;
    private javax.swing.JLabel priceLbl4;
    private javax.swing.JLabel priceLbl5;
    private javax.swing.JLabel priceLbl6;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}