package user_Interface;

public class RateGUI extends javax.swing.JFrame {

    public RateGUI() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratePanel = new javax.swing.JPanel();
        submitRateBtn = new javax.swing.JButton();
        star1 = new javax.swing.JButton();
        star2 = new javax.swing.JButton();
        star3 = new javax.swing.JButton();
        star4 = new javax.swing.JButton();
        star5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(470, 200));
        setMinimumSize(new java.awt.Dimension(470, 200));
        setResizable(false);
        getContentPane().setLayout(null);

        ratePanel.setBackground(new java.awt.Color(102, 102, 255));
        ratePanel.setMaximumSize(new java.awt.Dimension(470, 200));
        ratePanel.setLayout(null);

        submitRateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/submitsmall.png"))); // NOI18N
        submitRateBtn.setBorderPainted(false);
        submitRateBtn.setContentAreaFilled(false);
        submitRateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitRateBtnActionPerformed(evt);
            }
        });
        ratePanel.add(submitRateBtn);
        submitRateBtn.setBounds(184, 134, 100, 41);

        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png"))); // NOI18N
        star1.setMaximumSize(new java.awt.Dimension(50, 50));
        star1.setMinimumSize(new java.awt.Dimension(50, 50));
        star1.setPreferredSize(new java.awt.Dimension(50, 50));
        star1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star1ActionPerformed(evt);
            }
        });
        ratePanel.add(star1);
        star1.setBounds(89, 66, 50, 50);

        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png"))); // NOI18N
        star2.setMaximumSize(new java.awt.Dimension(50, 50));
        star2.setMinimumSize(new java.awt.Dimension(50, 50));
        star2.setPreferredSize(new java.awt.Dimension(50, 50));
        star2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star2ActionPerformed(evt);
            }
        });
        ratePanel.add(star2);
        star2.setBounds(149, 66, 50, 50);

        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png"))); // NOI18N
        star3.setMaximumSize(new java.awt.Dimension(50, 50));
        star3.setMinimumSize(new java.awt.Dimension(50, 50));
        star3.setPreferredSize(new java.awt.Dimension(50, 50));
        star3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star3ActionPerformed(evt);
            }
        });
        ratePanel.add(star3);
        star3.setBounds(209, 66, 50, 50);

        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png"))); // NOI18N
        star4.setMaximumSize(new java.awt.Dimension(50, 50));
        star4.setMinimumSize(new java.awt.Dimension(50, 50));
        star4.setPreferredSize(new java.awt.Dimension(50, 50));
        star4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star4ActionPerformed(evt);
            }
        });
        ratePanel.add(star4);
        star4.setBounds(269, 66, 50, 50);

        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png"))); // NOI18N
        star5.setMaximumSize(new java.awt.Dimension(50, 50));
        star5.setMinimumSize(new java.awt.Dimension(50, 50));
        star5.setPreferredSize(new java.awt.Dimension(50, 50));
        star5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star5ActionPerformed(evt);
            }
        });
        ratePanel.add(star5);
        star5.setBounds(329, 66, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rate2.png"))); // NOI18N
        ratePanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 200);

        getContentPane().add(ratePanel);
        ratePanel.setBounds(0, 0, 470, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitRateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitRateBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_submitRateBtnActionPerformed

    private void star1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star1ActionPerformed
        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png")));
        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png")));
        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png")));
        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png")));
    }//GEN-LAST:event_star1ActionPerformed

    private void star2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star2ActionPerformed
        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png")));
        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png")));
        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png")));
    }//GEN-LAST:event_star2ActionPerformed

    private void star3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star3ActionPerformed
        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png")));
        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png")));
    }//GEN-LAST:event_star3ActionPerformed

    private void star4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star4ActionPerformed
        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starDark.png")));
    }//GEN-LAST:event_star4ActionPerformed

    private void star5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star5ActionPerformed
        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/starLight.png")));
    }//GEN-LAST:event_star5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RateGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel ratePanel;
    private javax.swing.JButton star1;
    private javax.swing.JButton star2;
    private javax.swing.JButton star3;
    private javax.swing.JButton star4;
    private javax.swing.JButton star5;
    private javax.swing.JButton submitRateBtn;
    // End of variables declaration//GEN-END:variables
}