package user_Interface;

import Games.HangmanGUI;
import Games.TimeGUI;
import Games.WordSearchGUI;
import UserData.UserData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class ThirdAndForthGameSeletionGUI extends javax.swing.JFrame {

    TimeGUI myTimeGame;
    HangmanGUI myHammanGame;
    WordSearchGUI myWordSearchGame;

    public UserData myUser = new UserData();

    // for avatar image
    ImageIcon image;
    String avatar;
    String uName;

    //DB conncetion
    Connection conn;
    String url = "jdbc:mysql://sql3.freemysqlhosting.net/";
    String db = "sql368113";
    String driver = "com.mysql.jdbc.Driver";
    String user = "sql368113";
    String pass = "qG9*eZ8*";

    private ThirdAndForthGameSeletionGUI() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setUserData(UserData player) {
        this.myUser = player;
    }

    public ThirdAndForthGameSeletionGUI(UserData player) {
        initComponents();
        setLocationRelativeTo(null);

        this.myUser = player;

        AvailableTa.setVisible(false);

        //get name for start of database connection
        uName = myUser.getName();

        try {
            // connect to db here stated above
            conn = DriverManager.getConnection(url + db, user, pass);
        } catch (SQLException e) {
            System.out.println("SQL Exception:" + e.toString());
        }

        getPlayer();

        //set name
        nameLbl.setText(uName);

        //set avatar
        avatar = myUser.getAvatar();
        image = new ImageIcon(avatar);
        avatarLbl.setIcon(image);

        //set coins
        int coins = myUser.getCoins();
        String CoinTxt = String.valueOf(coins);
        coinsLbl.setText(CoinTxt + " coins");

    }

    public void getPlayer() {
        try {

            Statement st = conn.createStatement();
            ResultSet rs1 = st.executeQuery("select * from users WHERE name = '" + uName + "';");
            if (rs1.next()) {
                myUser.setCoins(rs1.getInt("coins"));
            } else {
                System.out.println("error test 1");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThirdAndForthGameSeletionGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        timeRbtn = new javax.swing.JRadioButton();
        wordsearchRBtn = new javax.swing.JRadioButton();
        hangmanRBtn = new javax.swing.JRadioButton();
        launchBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        selectionLbl1 = new javax.swing.JLabel();
        avatarLbl = new javax.swing.JLabel();
        ProfileBtn = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        coinsPicLbl = new javax.swing.JLabel();
        coinsLbl = new javax.swing.JLabel();
        AvailableTa = new javax.swing.JTextArea();
        bgkrLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        buttonGroup1.add(timeRbtn);
        timeRbtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        timeRbtn.setText("Time Game");
        timeRbtn.setOpaque(false);
        timeRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeRbtnActionPerformed(evt);
            }
        });
        jPanel1.add(timeRbtn);
        timeRbtn.setBounds(380, 200, 170, 29);

        buttonGroup1.add(wordsearchRBtn);
        wordsearchRBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        wordsearchRBtn.setText("Word Search Game");
        wordsearchRBtn.setOpaque(false);
        wordsearchRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsearchRBtnActionPerformed(evt);
            }
        });
        jPanel1.add(wordsearchRBtn);
        wordsearchRBtn.setBounds(380, 300, 210, 29);

        buttonGroup1.add(hangmanRBtn);
        hangmanRBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        hangmanRBtn.setText("Guess The Word Game");
        hangmanRBtn.setOpaque(false);
        hangmanRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hangmanRBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hangmanRBtn);
        hangmanRBtn.setBounds(380, 250, 220, 29);

        launchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LAUNCHbtn.png"))); // NOI18N
        launchBtn.setBorderPainted(false);
        launchBtn.setContentAreaFilled(false);
        launchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(launchBtn);
        launchBtn.setBounds(380, 400, 180, 90);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeBtn.png"))); // NOI18N
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setMaximumSize(new java.awt.Dimension(85, 32));
        homeBtn.setMinimumSize(new java.awt.Dimension(85, 32));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn);
        homeBtn.setBounds(0, 0, 85, 32);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backBtn.png"))); // NOI18N
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setMaximumSize(new java.awt.Dimension(85, 32));
        backBtn.setMinimumSize(new java.awt.Dimension(85, 32));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(90, 0, 85, 32);

        selectionLbl1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        selectionLbl1.setText("Select one game and press \"LAUNCH GAME\" to begin");
        jPanel1.add(selectionLbl1);
        selectionLbl1.setBounds(250, 120, 450, 32);

        avatarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guest.png"))); // NOI18N
        jPanel1.add(avatarLbl);
        avatarLbl.setBounds(670, 0, 80, 100);

        ProfileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileB.png"))); // NOI18N
        ProfileBtn.setBorderPainted(false);
        ProfileBtn.setContentAreaFilled(false);
        ProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ProfileBtn);
        ProfileBtn.setBounds(760, 70, 120, 40);

        nameLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        nameLbl.setText("Name");
        jPanel1.add(nameLbl);
        nameLbl.setBounds(760, 10, 120, 21);

        coinsPicLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coins.png"))); // NOI18N
        jPanel1.add(coinsPicLbl);
        coinsPicLbl.setBounds(760, 30, 30, 30);

        coinsLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(coinsLbl);
        coinsLbl.setBounds(800, 34, 70, 20);

        AvailableTa.setBackground(new java.awt.Color(102, 255, 204));
        AvailableTa.setColumns(20);
        AvailableTa.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        AvailableTa.setLineWrap(true);
        AvailableTa.setRows(5);
        AvailableTa.setText("Coins available in this game!");
        AvailableTa.setWrapStyleWord(true);
        AvailableTa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(AvailableTa);
        AvailableTa.setBounds(650, 250, 170, 20);

        bgkrLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ageSel.png"))); // NOI18N
        jPanel1.add(bgkrLbl);
        bgkrLbl.setBounds(0, 0, 900, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void launchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchBtnActionPerformed
        if (timeRbtn.isSelected()) {
            myTimeGame = new TimeGUI(myUser);
            myTimeGame.setVisible(true);

            // set questions and answers for time game
            String[] Questions = {"How many hours are in a quarter of a day?", "2 days 6 hours + 1 day 5 hours is equal to?", "Jaden's maths class starts at 10:20 A.M and lasts for 1 hour and 5 minutes. After maths class, Jaden has recess for 45 minutes. What time does Jaden's recess end?", "If sinead finishes football practice at 4:47 and she arrives home at 9:41. How long did it take Sinead to get home", "It takes John 25 minutes to walk to the car park and 45 to drive to work. At what time should he get out of the house in order to get to work at 9:00 a.m.?", "Paul can eat a sixth of a pizza in two minutes. While It takes Billy 3 minutes to eat one quarter of the a pizza. If John and Billy start eating one pizza each, who will finish first?"};
            String[] Answer1 = {"9", "3 days 11 hours", "11:10 A.M.", "4 hours 54 minutes", "7:35 a.m.", "Paul - 13 minutes"};
            String[] Answer2 = {"12", "3 days 15 hours", "12:00 P.M.", "5 hours 0 minutes", "7:50 a.m.", "Billy - 9 minutes"};
            String[] Answer3 = {"6", "2 days 23 hours", "12:15 P.M.", "4 hours 48 minutes", "7:45 a.m.", "At the same time - 12 minutes"};
            String[] Answer4 = {"5", "3 days 3 hours", "12:10 P.M.", "5 hours 11 minutes", "8:00 a.m.", "At the same time - 15 minutes"};
            String[] Correct = {"6", "3 days 11 hours", "12:10 P.M.", "4 hours 54 minutes", "7:50 a.m.", "At the same time - 12 minutes"};
            myTimeGame.setAnswers(Questions, Answer1, Answer2, Answer3, Answer4, Correct);
        } else if (hangmanRBtn.isSelected()) {
            myHammanGame = new HangmanGUI(myUser);
            myHammanGame.setVisible(true);
        } else {
            myWordSearchGame = new WordSearchGUI(myUser);
            myWordSearchGame.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_launchBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeGUI myHome = new HomeGUI(myUser);
        myHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        ChildAgeSelectionGUI mySecectionGUI = new ChildAgeSelectionGUI(myUser);
        mySecectionGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void ProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileBtnActionPerformed
        if (uName.equals("Guest")) {
            JOptionPane.showMessageDialog(null, "You must be logged in to access profile");
        } else {
            Profile selectionGUI = new Profile(myUser);
            selectionGUI.setUserData(myUser);
            selectionGUI.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ProfileBtnActionPerformed

    private void timeRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeRbtnActionPerformed
        AvailableTa.setVisible(true);
    }//GEN-LAST:event_timeRbtnActionPerformed

    private void hangmanRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hangmanRBtnActionPerformed
        AvailableTa.setVisible(false);
    }//GEN-LAST:event_hangmanRBtnActionPerformed

    private void wordsearchRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsearchRBtnActionPerformed
        AvailableTa.setVisible(true);
    }//GEN-LAST:event_wordsearchRBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThirdAndForthGameSeletionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThirdAndForthGameSeletionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThirdAndForthGameSeletionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdAndForthGameSeletionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThirdAndForthGameSeletionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AvailableTa;
    private javax.swing.JButton ProfileBtn;
    private javax.swing.JLabel avatarLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bgkrLbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel coinsLbl;
    private javax.swing.JLabel coinsPicLbl;
    private javax.swing.JRadioButton hangmanRBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton launchBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel selectionLbl1;
    private javax.swing.JRadioButton timeRbtn;
    private javax.swing.JRadioButton wordsearchRBtn;
    // End of variables declaration//GEN-END:variables
}